// Next
import type { Metadata } from "next";

// Global Styles
import "@/assets/styles/sass/_index.scss";

// Redux Provider
import ReduxProvider from "@/plugins/redux/provider";

// Auth Route
import ProtectedAuthRoute from "./protectedAuthRoute";

// Interfaces
import { type IChildrenProps } from "@/features/app/interfaces";

export const metadata: Metadata = {
  title: "POSME",
  description: "Generated by create next app",
};

const RootLayout: React.FC<IChildrenProps> = ({ children }) => (
  <html lang="en">
    <body>
      <ReduxProvider>
        <ProtectedAuthRoute>{children}</ProtectedAuthRoute>
      </ReduxProvider>
    </body>
  </html>
);

export default RootLayout;
