import type { Metadata } from "next";

import "@/assets/styles/sass/index.scss";

import { type IAppChildrenProps } from "@/features/app/interfaces";
import NextAuthProvider from "@/plugins/next-auth";
import ReduxProvider from "@/plugins/redux/provider";
export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "POSME",
};

const RootLayout = ({ children }: IAppChildrenProps) => (
  <html lang="en">
    <body>
      <ReduxProvider>
        <NextAuthProvider>{children}</NextAuthProvider>
      </ReduxProvider>
    </body>
  </html>
);

export default RootLayout;
