// Next
import type { Metadata } from "next";

// Global Styles
import "@/assets/styles/sass/_index.scss";

// Auth Route
import { ProtectedAuth } from "@/features/app/components";
// Interfaces
import { type IAppChildrenProps } from "@/features/app/interfaces";
// Next Auth
import NextAuthProvider from "@/plugins/next-auth";
// Redux Provider
import ReduxProvider from "@/plugins/redux/provider";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "POSME",
};

const RootLayout = ({ children }: IAppChildrenProps) => (
  <html lang="en">
    <body>
      <ReduxProvider>
        <NextAuthProvider>
          <ProtectedAuth>{children}</ProtectedAuth>
        </NextAuthProvider>
      </ReduxProvider>
    </body>
  </html>
);

export default RootLayout;
